<!--
    Type "x" between the square brackets to check the
    box. By submitting this issue you understand that
    if this box isn't checked or information isn't
    filled appropriately, it may be closed without
    consideration.
-->
[] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

<!-- Replace the placeholders -->
<!--
    You can get this by right-clicking the tray icon and
    pressing "Advanced" > "About". If for any reason this
    doesn't works, submit the OS Build from "System" >
    "About" in the Settings app as well as the app version
    from "Apps" > "Apps & features" > "TranslucentTB" >
    "Advanced options" also in the Settings app.
-->
 - Version information: Box version 2.0
<!-- What you do that triggers the problem -->
 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.
<!-- What should happen -->
 - Expected results: The box sits on the table.
<!-- What happens instead -->
 - Actual results: The box disappears spontaneously once
   put on the table.
<!--
    Other things that you feel could help in diagnosing
    the problem
-->
 - Other: The box I ordered was damaged.
